config/routes.rb
Rails.application.routes.draw do
	root'pages#home'
	get '/restuarants' => 'pages#restuarants'
	get '/attractions' => 'pages#attractions'

	resources :messages
	
	


	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	validates :saying, presence: true
	validates :topic, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def new
		@message = Message.new
	end	

	def create
		Message.create(message_params)
		redirect_to messages_path
	end	

	def index
		@message = Message.all
	end	

	private

	def message_params
		params.require(:message).permit(:topic, :saying)
	end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end	

	def sites
	end
	
	def attractions
	end

	def restuarants
	end
		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restuarants_helper.rb
module RestuarantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelSantaCruz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
     
     <%=link_to image_tag("santacruzca.png"), root_path, class: 'navbar-brand' %>

     
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            
            <%= link_to 'Attractions', attractions_path, class: 'navbar-brand' %>
          </li>
          
          <li class="nav-item">
            <%= link_to 'Restuarants', restuarants_path, class: 'navbar-brand' %>
          </li>

          <li class="nav-item">
            <%= link_to 'Add a Message', new_message_path, class: 'navbar-brand' %>
          </l> 

          <li class="nav-item">
            <%= link_to 'Messages', messages_path, class: 'navbar-brand' %>
          </li> 
          
 
          
        </div>
        </ul>
      </div>
    </nav>



    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<h1>Messages</h1>

<div class="booyah-box col-10 offset-1">	
	<% @message.each do |message| %>	
		<%= message.topic %>
		<%= message.saying %>
	<% end %>	
</div>	

app/views/messages/new.html.erb
<h2>Add a Message</h2>

<br />

<div class="booyah-box col-10 offset-1">	
	<%= simple_form_for Message.new do |f| %>
		<%= f.input :topic %>
		<%= f.input :saying %>
		<br />
		<%= f.submit 'Share', class: 'btn btn-danger' %>
	<% end %>	
</div>	

<br />
<br />
<br />

app/views/pages/attractions.html.erb
<h2>So many activites to choose from</h2>

<br />

<div class="booyah-box col-10 offset-1">
	<div class="pic1"><%= image_tag "boardwalk4.jpg" %></div> 	
		<u><h3><a href="https://beachboardwalk.com/" target="_blank">Santa Cruz Beach Boarwalk</a></h3></u>
			<p>Located right on the shoreline of the Monterey Bay, the Santa Cruz beach boarwalk is one of the oldest surving amusement parks, and one of the many few remaining on the West Coast. Days can be spent soaking up sun on the beach or riding many of the amusement rides. The most iconic ride is the Giant Dipper. Built in 1924, this coaster is one of the last wooden coasters and has gained fame world wide. Climb the 70 foot track and take in beautiful sights of the coast before taking the plunge. During the summers when the park is open daily, weekly concerts are hosted on the beach every Friday evening.</p> 
</div>	
		
		


<br /><br /><br />		

<div class="booyah-box col-10 offset-1">
	<div class="village"><%= image_tag "village3.jpg" %></div>
		<u><h3><a href="https://www.capitolavillage.com/" target="_blank">Capitola Village</a></h3></u>	
			<p>Hidden away about fifteen minutes from the business of downtown Santa Cruz, Capitola Village is a unique spot on the water. Walk along the esplanade and discover great restuarants with spectacular views of the bay. This sweet little spot has it's own beauty. Historic train tracks run acorss the the hill above. Stand on the bridge and get a sweeping view of the water. It's the perfect place to grab some lunch and head to the beach as it's just off the esplanade path.</p>
</div>	

<br /><br /><br />

<div class="booyah-box col-10 offset-1">
	<div class="pic3"><%= image_tag "jelly.jpg" %></div>
		<u><h3><a href="https://www.montereybayaquarium.org/" target="_blank">Monterey Bay Aquarium</a></h3></u>
			<p>Located at the south-end of the bay, The Monterey Bay Aquarium is a must when visiting the central coast. Opened in 1984, this aquarium focuses heavily on marine conversation and wildlife rehabilitation. The aquarium also holds educational programs for those interested in marine ecology. Many different exhibits are offered for viewing so there is something for everyone to see and experience. From penguins to batrays to great white sharks, this aquarium works with a diverse range of animals.</p>
</div>	

<br /><br /><br />

<div class="booyah-box col-10 offset-1">
	<div class="train"><%= image_tag "roar.jpg" %></div>
		<u><h3><a href="https://www.roaringcamp.com/" target="_blank">Roaring Camp Railroads</a></h3></u>
			<p>Located in the Santa Cruz Mountains, Roaring Camp Railroads is a fun place for the whole family. Board a locomotive and enjoy the ride through the scenic forests down to the Santa Cruz Beach Boardwalk. Feel immersed in the grove of redwood trees and enjoy the beauty of the nature around you. You might even see a famous banana slug. After a fun day at the beach, you can board the train and head into the mountains for your trip back.</p>
</div>

<br /><br /><br />

<div class="booyah-box col-10 offset-1">
	<div class="ocean"><%= image_tag "westcliff2.jpg"%></div>
		<u><h3>West Cliff Drive</h3></u>
		<p>A favoirte spot for locals, West Cliff Drive is a stretch of coast with some of the best views in the town. You can walk/drive/or ride bikes along this stretch. Stop at the Surf Museum and learn more about the towns surf history. The iconic lighthouse sits on West Cliff and makes a great spot for pictures. One of Santa Cruz's famous famous surf spots, Steamer's Lane, is visible from West Cliff so you're sure to see some surfers catching waves below.</p>		
</div>

<br /><br /><br />

<div class="booyah-box col-10 offset-1">
	<div class="bridges"><%= image_tag "natural2.jpg" %></div>
		<u><h3><a href="http://www.parks.ca.gov/?page_id=541" target="_blank">Natural Bridges</a></h3></u>
			<p>Located at the end of West Cliff Drive, this California state park known for its feature of a natural bridge across the beach, Natural Bridges is a local favorite for beautiful sights on the ocean. The park is also a hotspot to see the migrations of Monarch Butterflies. The Butterfly Natural Reserve is home to over 150,000 monarch butterflies during the months of October through early February.</p>
</div>	

app/views/pages/home.html.erb
<h1>Welcome to one of the most scenic towns!</h1>

app/views/pages/restuarants.html.erb
<h2>Find delicious food</h2>

<br /><br /><br />

<div class="booyah-box col-10 offset-1">		
	<u><h3><a href="https://www.shadowbrook-capitola.com/" target="_blank">Shadowbrook</a></h3></u>
		<p>If you're looking for a more formal restuarant with delicious food, look no further. Shadowbrook is located just up from Capitola Village, tucked away on the hillside. Parking is on the street and then you can either take the gondola down to the main building, or walk down through the landscaped gardens. If you sit on their patio, you can enjoy great views of the Soquel River as it flows in to Capitola Village. The menu primarily consists of delicious pastas, steaks, and seafood.</p>
</div>	

<br /><br /><br >

<div class="booyah-box col-10 offset-1">	
	<u><h3><a href="http://www.crowsnest-santacruz.com/" target="_blank">Crows Nest</a></h3></u>
		<p>Located right at the mouth of the Santa Cruz Harbor, the Crows Nest is one of the best spots for great food and amazing ocean views. They offer a wide range of food from burgers and pasta to fresh-caught seafood. Sit on the deck and enjoy the sun while looking out over the coastal beaches. During the summers on Wednesday nights, watch the local sailboat races on the water infront of you.</p>
</div>
	

<br /><br /><br />

<div class="booyah-box col-10 offset-1">	
	<u><h3><a href="http://www.rivafishhouse.com/" target="_blank">Riva Fish House</a></h3></u>
		<p>Open for lunch and dinner, this great spot is located right on the Santa Cruz Warf. Riva Fish House offeres primarily seafood and sandwiches. Look out the window from your table and take in the amazing marine life around you. After a great meal, enjoy a walk down the warf and take in the beautiful sites of the coast. At the very end of the warf, you can usually hear the sea lions as the relax on the planks below.</p>
	
</div>	